import { motion } from 'framer-motion';
import { Eye } from 'lucide-react';
import { useState } from 'react';

const featuredCreations = [
  { id: 1, image: '/assets/featured/creation-1.jpg', title: 'Cosmic Nebula' },
  { id: 2, image: '/assets/featured/creation-2.jpg', title: 'Cyberpunk City' },
  { id: 3, image: '/assets/featured/creation-3.jpg', title: 'Magical Forest' },
  { id: 4, image: '/assets/featured/creation-4.jpg', title: 'Abstract Waves' },
  { id: 5, image: '/assets/featured/creation-5.jpg', title: 'Underwater Paradise' },
  { id: 6, image: '/assets/featured/creation-6.jpg', title: 'Dragon Sunset' },
  { id: 7, image: '/assets/featured/creation-7.jpg', title: 'Floating Islands' },
  { id: 8, image: '/assets/featured/creation-8.jpg', title: 'AI Humanoid' },
  { id: 9, image: '/assets/featured/creation-9.jpg', title: 'Cosmic Portal' },
];

const FeaturedGallery = () => {
  const [hoveredId, setHoveredId] = useState<number | null>(null);

  return (
    <section className="py-12">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="text-center space-y-4 mb-12"
      >
        <h2 className="text-4xl md:text-5xl font-bold bg-gradient-glow bg-clip-text text-transparent">
          ✨ What Others Are Creating
        </h2>
        <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
          Explore stunning visuals generated by the community
        </p>
      </motion.div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {featuredCreations.map((creation, index) => (
          <motion.div
            key={creation.id}
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.4, delay: index * 0.1 }}
            onHoverStart={() => setHoveredId(creation.id)}
            onHoverEnd={() => setHoveredId(null)}
            className="relative group cursor-pointer overflow-hidden rounded-2xl border border-border/50 backdrop-blur-glass bg-card/60"
            whileHover={{ scale: 1.05 }}
          >
            <div className="aspect-video relative overflow-hidden">
              <img
                src={creation.image}
                alt={creation.title}
                className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
                loading="lazy"
              />
              
              {/* Hover Overlay */}
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: hoveredId === creation.id ? 1 : 0 }}
                transition={{ duration: 0.3 }}
                className="absolute inset-0 bg-gradient-to-t from-background/90 via-background/50 to-transparent flex items-end justify-center pb-8"
              >
                <div className="flex items-center gap-2 text-foreground font-semibold">
                  <Eye className="w-5 h-5" />
                  <span>View Creation</span>
                </div>
              </motion.div>
            </div>

            {/* Card Footer */}
            <div className="p-4 bg-card/80 backdrop-blur-sm">
              <h3 className="font-semibold text-foreground mb-1">{creation.title}</h3>
              <p className="text-sm text-muted-foreground">Created by community</p>
            </div>

            {/* Glow Effect on Hover */}
            {hoveredId === creation.id && (
              <div className="absolute inset-0 shadow-glow-violet pointer-events-none rounded-2xl" />
            )}
          </motion.div>
        ))}
      </div>
    </section>
  );
};

export default FeaturedGallery;
